### ISSUE TITLE
Storybook: modal with form

### ISSUE THREAD

**Issue by OFK0** [Teknasyon/rocket-ui#239]
Hi,

In storybook, modal with form example is not working.

https://teknasyon.github.io/rocket-ui/?path=/story/components-modal--with-form

<img width="808" alt="image" src="https://github.com/Teknasyon/rocket-ui/assets/28747412/5ef7ed3f-957e-4e9b-a497-78e571b2335b">

**Comment by gokh4nozturk** [comment]
Hi @OFK0,

This issue is resolved. Thanks for the feedback.
